#!/bin/bash

export WEB_HOST_NAME="caffestazione.com.au"
export INDEX_HTML_DESCRIPTION="An Italian Caffe catering for all needs including breakfast and lunch options. Caffe Stazione's Pizza is genuine Italian style served by the slice and possibly the best in Melbourne. There are healthy, Gluten Free options and salads, not to mention a large cake and sweet display all filled with house made delicate cakes, sweets, pastries and biscuits."
export PARCEL_OPTIONS="--target webComponents --target spa"
export DIST_FLATTEN="true"

export COV_BRANCHES=0
export COV_LINES=0
export COV_FUNCTIONS=0
export COV_STATEMENTS=0

# This project

export ADDRESS_LINE_1="171-175 Maroondah Hwy"
export ADDRESS_LINE_2="Ringwood, VIC, Australia 3134"
export PHONE="(03) 8845 9108"
export EMAIL="stazionecaffe@gmail.com"
export CATERING_URL="https://catering.caffestazione.com.au"
export MON_TO_FRI_HOURS="7—4"
export SAT_HOURS="8—4"
export SUN_HOURS="9—4"

export MIXPANEL_TOKEN="6871a18d371683daa377180e39c625ca"
